// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yylekjaribjuythpmtya.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl5bGVramFyaWJqdXl0aHBtdHlhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyMDQ4OTIsImV4cCI6MjA3Mzc4MDg5Mn0.agCGyKmHfLCRcI-8zv_f6Ag3kXw1-tERzQxy6BsCqfU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});